server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api                 #被过滤的访问路径的前缀为/api
  routes:
    item-service: /item/**    #将路径为  /item/** 都路由到item-service微服务
    upload-service: /upload/**                          #如http://localhost:10010/api/item/user ----》item-service/user
    search-service: /search/**   #路由到搜索微服务